# Numpy

To install numpy run:

```
pip install numpy
```

In a terminal, or

In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print("Numpy version:", np.__version__)

Numpy version: 2.3.4


## Creating arrays from lists

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr_1d)

[1 2 3 4 5]


In [6]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


### Other array creation methods

In [8]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
const_array = np.full((3,4), 1.0)
print(const_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Array attributes

In [15]:
const_array.shape

(3, 4)

In [16]:
const_array.dtype

dtype('float64')

In [17]:
const_array.nbytes

96

## Array operations

### Arithmetic

In [30]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = np.array([1])

In [24]:
print(a + b)

[11 22 33 44]


In [25]:
print(a - b)

[ 9 18 27 36]


In [31]:
print(a + c)

[11 21 31 41]


In [32]:
print(a * 2)

[20 40 60 80]


### Statistics

In [27]:
print(np.mean(a))

25.0


In [28]:
print(np.sum(a))

100
