# Import Numpy

In [1]:
import numpy as np

#1. Creating a NumPy Array
- Create a NumPy array with the following integers: 5, 10, 15, 20, 25, 30.

- Then, create a 2D array of shape (2, 3) using the same numbers.

In [2]:
my_array = np.array([5, 10, 15, 20, 25, 30])
my_array

array([ 5, 10, 15, 20, 25, 30])

In [3]:
my_array2 = my_array.reshape(2,3)
my_array2

array([[ 5, 10, 15],
       [20, 25, 30]])

#2. Array Functions

##Given the array:

    arr = np.array([3, -5, 7, 2, -8, 0])
  
###Use NumPy functions to:

- Find the absolute values of the elements
- Sort the array
- Return only the positive numbers

In [4]:
arr = np.array([3, -5, 7, 2, -8, 0])

abs_val = np.abs(arr)
abs_val

array([3, 5, 7, 2, 8, 0])

In [5]:
arr.sort()
arr

array([-8, -5,  0,  2,  3,  7])

In [6]:
positive_arr = arr[arr>0]
positive_arr

array([2, 3, 7])

#3. Arithmetic Operations
##Given two arrays:
```
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])
```



###Perform the following element-wise operations:

- Addition
- Multiplication
- Raise each element of **a** to the power of the corresponding element in **b**

In [7]:
#Add a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add_arr = a+b #[1+4, 2+5, 3+6]
add_arr

array([5, 7, 9])

In [8]:
#Multiply a and b
mul_arr = a*b # == [1*4, 2*5, 3*6]
mul_arr

array([ 4, 10, 18])

In [9]:
#Exponentiation of a to b
exp_arr = a**b # ==[1^4, 2^5, 3^6]
exp_arr

array([  1,  32, 729])

#4. Statistical Functions
###Generate a NumPy array with 20 random integers between 1 and 100.

Using your array Calculate:
-  mean
- median
- standard deviation
- maximum and minimum values

In [10]:
#generate the array
arr = np.random.randint(1,100,20)
arr

array([63, 84, 27, 83,  9, 31, 37, 30, 14,  8, 65, 34, 20, 74, 65, 64, 82,
       51, 39, 51])

In [11]:
#array mean
np.mean(arr)

np.float64(46.55)

In [12]:
#array median
np.median(arr)

np.float64(45.0)

In [13]:
#array standard deviation
np.std(arr)

np.float64(24.393595470942774)

In [14]:
#array max and min
np.max(arr), np.min(arr)

(np.int64(84), np.int64(8))

#5. Array Indexing (2 Problems)
##Problem 1:
- Create a 3x3 array filled with numbers from 1 to 9.
- Retrieve the element in the second row, third column.

##Problem 2:
###Given the array:
```
arr = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
```
- Access and print **all elements in the last column**.


In [15]:
#5.1
arr = np.arange(1,10).reshape(3,3) #arange() is simialr to the range() funition in python, but returns an array. Then just reshape to a 3x3
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#5.2
arr[1, -1] #Remember that the rows and columns are 0 indexed, like python lists.
           #So index 1,-1 is the (1 is the second element of in the sequence of rows, and -1 is the last item in that row)

np.int64(6)

#6. Slicing Arrays (2 Problems)
##Problem 1:
Given an array of numbers from 0 to 19:
- Extract every third element starting from index 2.

## Problem 2:
Given a 4x4 array:

```
arr = np.array([[10, 20, 30, 40],  
                [50, 60, 70, 80],  
                [90, 100, 110, 120],  
                [130, 140, 150, 160]])
```
- Extract the subarray containing the middle 2x2 elements.


In [17]:
#6.1
arr = np.arange(20)
my_arr = arr[arr % 3 == 2]

my_arr

array([ 2,  5,  8, 11, 14, 17])

In [18]:
#6.2
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])

arr[1:3, 1:3]

array([[ 60,  70],
       [100, 110]])