# Numpy Documentaion: https://numpy.org/doc/stable/

#NumPy Indexing

In [2]:
# Import Numpy
import numpy as np

## Problem 1: Integer Indexing



```
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
```

- Use Integer indexing to retrieve the value '80'

In [3]:
# Integer index the array, 'arr'
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr[-1][1]

np.int64(80)

## Problem 2: Indexing with an Array of Indices


```
arr = np.array([100, 200, 300, 400, 500])
indices = np.array([0, 2, 4])
```
- Use your 'indices' array to extract elements from the array, 'arr'

In [4]:
# Index the array 'arr' using the arrray 'indices'
arr = np.array([100, 200, 300, 400, 500])
indices = np.array([0, 2, 4])


arr[indices]

array([100, 300, 500])

##Problem 3: Boolean Indexing



```
arr = np.array([5, 15, 25, 35, 45])
```

- Use Boolean Indexing to extract all values from 'arr' which are greater than 20

In [5]:
# Generate your boolean array and assign it to the name, 'bool_arr'
arr = np.array([5, 15, 25, 35, 45])

bool_arr = arr > 20

In [6]:
# Use 'bool_arr' to index the original array 'arr'
arr[bool_arr]

array([25, 35, 45])

## Problem 4: Multi-dimensional Fancy Indexing

- Generate a 3x3 array with random numbers in the range 1-100


```
rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])
```
- Use the rows and cols array to extract the elements: (0,2), (1,0), and (2,1).


In [15]:
rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])

In [14]:
# Generate your 2D array
my_arr = np.random.randint(1, 101, (3, 3))
my_arr

array([[42, 21,  2],
       [73, 19, 29],
       [96, 55, 40]])

In [16]:
# Use Fancy Indexing to Extract elements : (0,2), (1,0), and (2,1)
my_arr[rows, cols]

array([ 2, 73, 55])

# Numpy Slicing

## Problem 1: Basic 1D Slicing



```
arr = np.array([10, 20, 30, 40, 50, 60])
```
- Use slicing to extract [20, 30, 40] from the array 'arr'


In [17]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [18]:
# Slice the array 'arr'
arr[1:4]

array([20, 30, 40])

## Problem 2: 2D Row Slicing




```
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
```
- Use slicing to extract the last two rows from arr


In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

In [21]:
# Slice the array 'arr' to extract the last two rows
arr[2:, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

## Problem 3: 2D Column Slicing



```
arr = np.array([[100, 200, 300, 400],
                [500, 600, 700, 800]])
```
- Use column slicing to extract only the middle two columns
- Save your slice to a new array called, 'my_slice'
- Use a numpy method to calculate the sum of all elements in your array, 'my_slice'


In [22]:
arr = np.array([[100, 200, 300, 400],
                [500, 600, 700, 800]])

In [26]:
# Extract the middle two columns from both rows in the array 'arr'
my_slice = arr[:, 1:3]
my_slice

array([[200, 300],
       [600, 700]])

In [29]:
# Calculate the sum of the elements in your array, 'my_slice'
my_slice.sum()

np.int64(1800)

In [30]:
# Calculate the sum of the elements in your array, 'my_slice'
np.sum(my_slice)

np.int64(1800)

## Problem 5: Reverse Slicing



```
arr = np.array([5, 10, 15, 20, 25, 30])
```
- Use slicing to reverse the array, 'arr'
- Save the reveresed array to the variable name, 'rev_arr'
- Use Integer indexing to access index 2 of your array, 'rev_arr'


In [31]:
arr = np.array([5, 10, 15, 20, 25, 30])

In [33]:
# Reverse the array, 'arr'
inverse_arr = arr[::-1]

inverse_arr

array([30, 25, 20, 15, 10,  5])

In [34]:
# Integer index your reversed array to access index 2
inverse_arr[2]

np.int64(20)